#!/usr/bin/env python3
"""Write the Husky A300 meshes, both from the SAME box/cylinder geometry (metres, robot frame):
  * binary STL for lidar3d_dds' self-filter,
  * OBJ for robot_concept / controller (robot node `path`: body width/depth and footprint hull).

HuskyA300.proto is a JS-templated PROTO, which lidar3d_dds' proto loader cannot parse, so the
self-filter gets the same geometry as a static mesh instead. Robot frame = the proto's:
+Y forward, +X right, +Z up, origin on the floor under the wheel centre.

KEEP IN SYNC with the defaults of webots-agri/protos/HuskyA300.proto.

Usage: gen_husky_selffilter_stl.py [out.stl [out.obj]]
  default out: robocomp-robolab/components/hardware/laser/lidar3d_dds/robots/HuskyA300/husky_a300.stl
               active_inference/robot_concept/meshes/husky_a300.obj
"""
import math
import pathlib
import struct
import sys

R, W = 0.1651, 0.1143            # wheel radius, width
HX, HY = 0.5708 / 2, 0.512 / 2   # half track, half wheelbase
INNER_W = 2 * HX - W - 0.02
MAST = (0.0, -0.25, 0.95)        # heliosTranslation
ZED = (0.0, 0.42, 0.55)          # zedTranslation


def box(cx, cy, cz, sx, sy, sz):
    x0, x1, y0, y1, z0, z1 = cx - sx / 2, cx + sx / 2, cy - sy / 2, cy + sy / 2, cz - sz / 2, cz + sz / 2
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    quads = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (2, 3, 7, 6), (1, 2, 6, 5), (3, 0, 4, 7)]
    return [(v[a], v[b], v[c]) for q in quads for a, b, c in ((q[0], q[1], q[2]), (q[0], q[2], q[3]))]


def wheel(cx, cy, cz, n=24):
    """Cylinder with its axis along X."""
    tris = []
    xl, xr = cx - W / 2, cx + W / 2
    for i in range(n):
        a0, a1 = 2 * math.pi * i / n, 2 * math.pi * (i + 1) / n
        p0 = (cy + R * math.cos(a0), cz + R * math.sin(a0))
        p1 = (cy + R * math.cos(a1), cz + R * math.sin(a1))
        tris += [((xl, *p0), (xr, *p0), (xr, *p1)), ((xl, *p0), (xr, *p1), (xl, *p1)),
                 ((xl, cy, cz), (xl, *p0), (xl, *p1)), ((xr, cy, cz), (xr, *p1), (xr, *p0))]
    return tris


def main():
    here = pathlib.Path(__file__).resolve()
    repo = here.parents[2]
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else (
        repo / "robocomp-robolab/components/hardware/laser/lidar3d_dds/robots/HuskyA300/husky_a300.stl")
    mast_base = 2 * R + 0.04
    mast_top = MAST[2] - 0.05
    tris = []
    tris += box(0, 0, R + 0.06, INNER_W, 0.80, 0.22)                       # chassis
    tris += box(0, 0, 2 * R + 0.025, 2 * HX + W, 0.86, 0.03)               # top plate
    tris += box(0, 0.47, R + 0.06, 2 * HX + W - 0.04, 0.05, 0.06)          # front bumper
    tris += box(0, -0.47, R + 0.06, 2 * HX + W - 0.04, 0.05, 0.06)         # rear bumper
    tris += box(MAST[0], MAST[1], (mast_base + mast_top) / 2, 0.04, 0.04, mast_top - mast_base)  # mast
    tris += box(ZED[0], ZED[1], ZED[2], 0.17, 0.03, 0.03)                  # zed body
    for sx in (-1, 1):
        for sy in (-1, 1):
            tris += wheel(sx * HX, sy * HY, R)

    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "wb") as f:
        f.write(b"HuskyA300 self-filter, metres, robot frame (+Y fwd, +X right, +Z up)".ljust(80, b" "))
        f.write(struct.pack("<I", len(tris)))
        for a, b, c in tris:
            u = [b[i] - a[i] for i in range(3)]
            v = [c[i] - a[i] for i in range(3)]
            nrm = (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])
            ln = math.sqrt(sum(x * x for x in nrm)) or 1.0
            f.write(struct.pack("<12fH", *(x / ln for x in nrm), *a, *b, *c, 0))
    print(f"wrote {out} ({len(tris)} triangles)")

    obj = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else (
        repo / "active_inference/robot_concept/meshes/husky_a300.obj")
    obj.parent.mkdir(parents=True, exist_ok=True)
    with open(obj, "w") as f:
        f.write("# HuskyA300 body, metres, robot frame (+Y fwd, +X right, +Z up). Generated by\n"
                "# webots-agri/tools/gen_husky_selffilter_stl.py -- do not edit by hand.\n")
        for k, (a, b, c) in enumerate(tris):
            for p in (a, b, c):
                f.write(f"v {p[0]:.5f} {p[1]:.5f} {p[2]:.5f}\n")
            f.write(f"f {3 * k + 1} {3 * k + 2} {3 * k + 3}\n")
    print(f"wrote {obj} ({len(tris)} faces)")


if __name__ == "__main__":
    main()
