#!/usr/bin/env python3
"""Write rows of YoungPalm into a Webots world, between the PALM_ROWS markers (plan.md, F3).

Spacing is derived from the Husky A300, not chosen by eye:
  * robot width 0.69 m (wheels outer, HuskyA300.proto), mast + GPS up to 1.02 m: the fronds are at
    mast height, so the CROWN, not the trunk, is what bounds the corridor;
  * YoungPalm crown radius ~0.6 m  ->  row spacing 2.5 m leaves a 1.3 m clear corridor, i.e. the robot
    plus ~0.3 m each side;
  * 1.5 m between palms in a row (crowns just touch: a continuous wall to drive along);
  * rows run south->north (+Y), centred on the origin, with >= 3 m headlands to the arena walls.

Usage: gen_palm_rows.py [world.wbt] [--rows 5] [--per-row 10] [--row-spacing 2.5] [--palm-spacing 1.5]
                        [--jitter 0.05] [--seed 7] [--z 0]
Prints the corridor centre lines and the field bounding box, for openfield_concept's Field.Polygon.
"""
import argparse
import pathlib
import random
import re

BEGIN = "# ---- PALM_ROWS BEGIN (generated by webots-agri/tools/gen_palm_rows.py; do not edit by hand) ----"
END = "# ---- PALM_ROWS END ----"
CROWN_RADIUS = 0.6
ROBOT_WIDTH = 0.69


def main():
    here = pathlib.Path(__file__).resolve().parent
    ap = argparse.ArgumentParser()
    ap.add_argument("world", nargs="?", default=str(here.parent / "worlds/husky_test.wbt"))
    ap.add_argument("--rows", type=int, default=5)
    ap.add_argument("--per-row", type=int, default=10)
    ap.add_argument("--row-spacing", type=float, default=2.5)
    ap.add_argument("--palm-spacing", type=float, default=1.5)
    ap.add_argument("--jitter", type=float, default=0.05, help="planting error, m (uniform)")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--z", type=float, default=0.0,
                    help="trunk base height, m (on a FieldTerrain bed: bedHeight minus a few cm so it sits IN the soil)")
    a = ap.parse_args()

    clear = a.row_spacing - 2 * CROWN_RADIUS
    if clear < ROBOT_WIDTH + 0.2:
        raise SystemExit(f"corridor {clear:.2f} m is too narrow for a {ROBOT_WIDTH} m robot")

    rng = random.Random(a.seed)
    xs = [(i - (a.rows - 1) / 2) * a.row_spacing for i in range(a.rows)]
    ys = [(j - (a.per_row - 1) / 2) * a.palm_spacing for j in range(a.per_row)]
    lines = [BEGIN]
    for i, x in enumerate(xs):
        for j, y in enumerate(ys):
            px = x + rng.uniform(-a.jitter, a.jitter)
            py = y + rng.uniform(-a.jitter, a.jitter)
            yaw = rng.uniform(-3.14159, 3.14159)
            lines.append(
                f'DEF PALM_R{i + 1}_{j + 1:02d} YoungPalm {{\n'
                f'  translation {px:.3f} {py:.3f} {a.z:.3f}\n'
                f'  rotation 0 0 1 {yaw:.3f}\n'
                f'  name "palm r{i + 1} p{j + 1}"\n'
                f'  seed {i * 100 + j + 1}\n'
                f'}}')
    lines.append(END)
    block = "\n".join(lines)

    world = pathlib.Path(a.world)
    text = world.read_text()
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        text = text.rstrip("\n") + "\n" + block + "\n"
    if 'EXTERNPROTO "../protos/YoungPalm.proto"' not in text:
        text = text.replace('EXTERNPROTO "../protos/HuskyA300.proto"',
                            'EXTERNPROTO "../protos/HuskyA300.proto"\nEXTERNPROTO "../protos/YoungPalm.proto"')
    world.write_text(text)

    corridors = [(xs[k] + xs[k + 1]) / 2 for k in range(len(xs) - 1)]
    print(f"{a.rows} rows x {a.per_row} palms -> {world}")
    print(f"  rows at x = {', '.join(f'{x:.2f}' for x in xs)}; palms y = {ys[0]:.2f} .. {ys[-1]:.2f}")
    print(f"  corridor centre lines x = {', '.join(f'{c:.2f}' for c in corridors)} "
          f"(clear width {clear:.2f} m for a {ROBOT_WIDTH} m robot)")
    print(f"  planted area: x {xs[0] - CROWN_RADIUS:.2f}..{xs[-1] + CROWN_RADIUS:.2f}, "
          f"y {ys[0] - CROWN_RADIUS:.2f}..{ys[-1] + CROWN_RADIUS:.2f}")


if __name__ == "__main__":
    main()
